services:
  caddy:
    container_name: caddy
    hostname: caddy
    image: caddy:latest
    environment:
      - SUBDOMAIN=${SUBDOMAIN}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - SSL_EMAIL=${SSL_EMAIL}
    networks: ['shared_network']
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./data/caddy:/data
      - ./caddy_config:/config
      - ./caddy_config/Caddyfile:/etc/caddy/Caddyfile
networks:
  shared_network:
    name: shared_network
    driver: bridge
    external: true