name: caddy
services:
  caddy:
    container_name: caddy
    hostname: caddy
    image: caddy:latest
    networks:
      - shared_network
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - ./data:/data
      - ./config:/etc/caddy
networks:
  shared_network:
    name: shared_network
    driver: bridge
    external: true